"""Suburb seed lists for the scraper.

Each entry is (suburb, postcode, state). State is needed because some
suburb names collide across states (Brighton, Paddington, Palm Beach, Hamilton).
"""

from __future__ import annotations

# ============================================================================
# Gold Coast LGA (postcodes 4207-4228) — original scope, all QLD.
# ============================================================================
GOLD_COAST_SUBURBS: list[tuple[str, str, str]] = [
    # ("Yatala", "4207", "QLD"),
    # ("Stapylton", "4207", "QLD"),
    # ("Steiglitz", "4207", "QLD"),
    # ("Alberton", "4207", "QLD"),
    # ("Luscombe", "4207", "QLD"),
    # ("Ormeau", "4208", "QLD"),
    # ("Ormeau Hills", "4208", "QLD"),
    # ("Jacobs Well", "4208", "QLD"),
    # ("Norwell", "4208", "QLD"),
    # ("Pimpama", "4209", "QLD"),
    # ("Coomera", "4209", "QLD"),
    # ("Upper Coomera", "4209", "QLD"),
    # ("Willow Vale", "4209", "QLD"),
    # ("Oxenford", "4210", "QLD"),
    # ("Maudsland", "4210", "QLD"),
    # ("Wongawallan", "4210", "QLD"),
    # ("Guanaba", "4210", "QLD"),
    # ("Pacific Pines", "4211", "QLD"),
    # ("Gaven", "4211", "QLD"),
    # ("Carrara", "4211", "QLD"),
    # ("Nerang", "4211", "QLD"),
    # ("Highland Park", "4211", "QLD"),
    # ("Advancetown", "4211", "QLD"),
    # ("Beechmont", "4211", "QLD"),
    # ("Mount Nathan", "4211", "QLD"),
    # ("Numinbah Valley", "4211", "QLD"),
    # ("Natural Bridge", "4211", "QLD"),
    # ("Hope Island", "4212", "QLD"),
    # ("Helensvale", "4212", "QLD"),
    # ("Worongary", "4213", "QLD"),
    # ("Mudgeeraba", "4213", "QLD"),
    # ("Bonogin", "4213", "QLD"),
    # ("Tallai", "4213", "QLD"),
    # ("Springbrook", "4213", "QLD"),
    # ("Arundel", "4214", "QLD"),
    # ("Parkwood", "4214", "QLD"),
    # ("Ashmore", "4214", "QLD"),
    # ("Molendinar", "4214", "QLD"),
    ("Labrador", "4215", "QLD"),
    ("Southport", "4215", "QLD"),
    # ("Coombabah", "4216", "QLD"),
    # ("Paradise Point", "4216", "QLD"),
    # ("Hollywell", "4216", "QLD"),
    # ("Runaway Bay", "4216", "QLD"),
    # ("Biggera Waters", "4216", "QLD"),
    # ("Bundall", "4217", "QLD"),
    ("Main Beach", "4217", "QLD"),
    ("Surfers Paradise", "4217", "QLD"),
    # ("Chevron Island", "4217", "QLD"),
    # ("Benowa", "4217", "QLD"),
    # ("Sorrento", "4217", "QLD"),
    ("Broadbeach", "4218", "QLD"),
    ("Broadbeach Waters", "4218", "QLD"),
    ("Mermaid Beach", "4218", "QLD"),
    ("Mermaid Waters", "4218", "QLD"),
    ("Nobby Beach", "4218", "QLD"),
    ("Miami", "4220", "QLD"),
    ("Burleigh Heads", "4220", "QLD"),
    ("Burleigh Waters", "4220", "QLD"),
    ("Palm Beach", "4221", "QLD"),
    ("Elanora", "4221", "QLD"),
    ("Currumbin", "4223", "QLD"),
    ("Currumbin Waters", "4223", "QLD"),
    ("Currumbin Valley", "4223", "QLD"),
    ("Tugun", "4224", "QLD"),
    ("Bilinga", "4225", "QLD"),
    ("Kirra", "4225", "QLD"),
    ("Coolangatta", "4225", "QLD"),
    ("Robina", "4226", "QLD"),
    ("Clear Island Waters", "4226", "QLD"),
    ("Merrimac", "4226", "QLD"),
    ("Varsity Lakes", "4227", "QLD"),
    ("Reedy Creek", "4227", "QLD"),
    ("Tallebudgera", "4228", "QLD"),
    ("Tallebudgera Valley", "4228", "QLD"),
]


# ============================================================================
# TARGET SUBURBS — wealthy areas where land scarcity makes duplex/triplex
# redevelopment economically viable. The thesis: high $/m² + small lots = the
# duplex game. Skips Tasmania and Darwin (no thesis match).
# ============================================================================
TARGET_SUBURBS: list[tuple[str, str, str]] = [
    # ---- Gold Coast beachside (subset of GOLD_COAST_SUBURBS focused on beach strip) ----
    ("Surfers Paradise", "4217", "QLD"),
    ("Main Beach", "4217", "QLD"),
    ("Broadbeach", "4218", "QLD"),
    ("Mermaid Beach", "4218", "QLD"),
    ("Mermaid Waters", "4218", "QLD"),
    ("Nobby Beach", "4218", "QLD"),
    ("Miami", "4220", "QLD"),
    ("Burleigh Heads", "4220", "QLD"),
    ("Palm Beach", "4221", "QLD"),
    ("Currumbin", "4223", "QLD"),
    ("Tugun", "4224", "QLD"),
    ("Bilinga", "4225", "QLD"),
    ("Kirra", "4225", "QLD"),
    ("Coolangatta", "4225", "QLD"),
    # ---- Sunshine Coast ----
    ("Noosa Heads", "4567", "QLD"),
    ("Sunshine Beach", "4567", "QLD"),
    ("Noosaville", "4566", "QLD"),
    ("Peregian Beach", "4573", "QLD"),
    ("Coolum Beach", "4573", "QLD"),
    ("Mooloolaba", "4557", "QLD"),
    ("Maroochydore", "4558", "QLD"),
    ("Cotton Tree", "4558", "QLD"),
    ("Caloundra", "4551", "QLD"),
    ("Kings Beach", "4551", "QLD"),
    ("Buderim", "4556", "QLD"),
    # ---- Northern Rivers / Byron ----
    ("Byron Bay", "2481", "NSW"),
    ("Suffolk Park", "2481", "NSW"),
    ("Brunswick Heads", "2483", "NSW"),
    ("Lennox Head", "2478", "NSW"),
    ("Bangalow", "2479", "NSW"),
    ("Mullumbimby", "2482", "NSW"),
    # ---- Newcastle ----
    ("Bar Beach", "2300", "NSW"),
    ("Cooks Hill", "2300", "NSW"),
    ("The Hill", "2300", "NSW"),
    ("Merewether", "2291", "NSW"),
    ("Newcastle East", "2300", "NSW"),
    ("Hamilton South", "2303", "NSW"),
    # ---- Central Coast ----
    ("Avoca Beach", "2251", "NSW"),
    ("Terrigal", "2260", "NSW"),
    ("Pearl Beach", "2256", "NSW"),
    ("MacMasters Beach", "2251", "NSW"),
    ("Killcare", "2257", "NSW"),
    ("Wamberal", "2260", "NSW"),
    ("Copacabana", "2251", "NSW"),
    # ---- Wollongong / Illawarra ----
    ("Thirroul", "2515", "NSW"),
    ("Austinmer", "2515", "NSW"),
    ("Bulli", "2516", "NSW"),
    ("Wollongong", "2500", "NSW"),
    ("North Wollongong", "2500", "NSW"),
    ("Coledale", "2515", "NSW"),
    # ---- Sydney East ----
    ("Bondi", "2026", "NSW"),
    ("Bondi Beach", "2026", "NSW"),
    ("Bondi Junction", "2022", "NSW"),
    ("Bronte", "2024", "NSW"),
    ("Tamarama", "2026", "NSW"),
    ("Coogee", "2034", "NSW"),
    ("Clovelly", "2031", "NSW"),
    ("Vaucluse", "2030", "NSW"),
    ("Bellevue Hill", "2023", "NSW"),
    ("Double Bay", "2028", "NSW"),
    ("Rose Bay", "2029", "NSW"),
    ("Paddington", "2021", "NSW"),
    ("Woollahra", "2025", "NSW"),
    ("Point Piper", "2027", "NSW"),
    ("Darling Point", "2027", "NSW"),
    ("Edgecliff", "2027", "NSW"),
    ("Randwick", "2031", "NSW"),
    # ---- Sydney North / Northern Beaches ----
    ("Mosman", "2088", "NSW"),
    ("Cremorne", "2090", "NSW"),
    ("Neutral Bay", "2089", "NSW"),
    ("Kirribilli", "2061", "NSW"),
    ("McMahons Point", "2060", "NSW"),
    ("Manly", "2095", "NSW"),
    ("Freshwater", "2096", "NSW"),
    ("Curl Curl", "2096", "NSW"),
    ("Dee Why", "2099", "NSW"),
    ("Collaroy", "2097", "NSW"),
    ("Avalon Beach", "2107", "NSW"),
    ("Whale Beach", "2107", "NSW"),
    ("Palm Beach", "2108", "NSW"),
    # ---- Sydney Inner West ----
    ("Balmain", "2041", "NSW"),
    ("Birchgrove", "2041", "NSW"),
    ("Rozelle", "2039", "NSW"),
    ("Glebe", "2037", "NSW"),
    ("Annandale", "2038", "NSW"),
    # ---- Brisbane inner / river ----
    ("Hamilton", "4007", "QLD"),
    ("Bulimba", "4171", "QLD"),
    ("Hawthorne", "4171", "QLD"),
    ("Ascot", "4007", "QLD"),
    ("New Farm", "4005", "QLD"),
    ("Teneriffe", "4005", "QLD"),
    ("Newstead", "4006", "QLD"),
    ("Paddington", "4064", "QLD"),
    ("Bardon", "4065", "QLD"),
    ("Toowong", "4066", "QLD"),
    ("Auchenflower", "4066", "QLD"),
    ("St Lucia", "4067", "QLD"),
    ("West End", "4101", "QLD"),
    ("Highgate Hill", "4101", "QLD"),
    ("Chelmer", "4068", "QLD"),
    ("Graceville", "4075", "QLD"),
    # ---- Melbourne inner east ----
    ("Toorak", "3142", "VIC"),
    ("South Yarra", "3141", "VIC"),
    ("Prahran", "3181", "VIC"),
    ("Windsor", "3181", "VIC"),
    ("Armadale", "3143", "VIC"),
    ("Malvern", "3144", "VIC"),
    ("Hawthorn", "3122", "VIC"),
    ("Kew", "3101", "VIC"),
    ("Camberwell", "3124", "VIC"),
    # ---- Melbourne bayside / inner ----
    ("Brighton", "3186", "VIC"),
    ("Hampton", "3188", "VIC"),
    ("Sandringham", "3191", "VIC"),
    ("Black Rock", "3193", "VIC"),
    ("Beaumaris", "3193", "VIC"),
    ("Mentone", "3194", "VIC"),
    ("Elwood", "3184", "VIC"),
    ("St Kilda", "3182", "VIC"),
    ("Albert Park", "3206", "VIC"),
    ("Middle Park", "3206", "VIC"),
    ("Port Melbourne", "3207", "VIC"),
    # ---- Mornington Peninsula ----
    ("Sorrento", "3943", "VIC"),
    ("Portsea", "3944", "VIC"),
    ("Blairgowrie", "3942", "VIC"),
    ("Rye", "3941", "VIC"),
    ("Mount Eliza", "3930", "VIC"),
    # ---- Perth wealthy / coastal ----
    ("Cottesloe", "6011", "WA"),
    ("Peppermint Grove", "6011", "WA"),
    ("Mosman Park", "6012", "WA"),
    ("Claremont", "6010", "WA"),
    ("Dalkeith", "6009", "WA"),
    ("Nedlands", "6009", "WA"),
    ("Subiaco", "6008", "WA"),
    ("City Beach", "6015", "WA"),
    ("Floreat", "6014", "WA"),
    ("Fremantle", "6160", "WA"),
    ("North Fremantle", "6159", "WA"),
    ("East Fremantle", "6158", "WA"),
    # ---- Adelaide wealthy / coastal ----
    ("North Adelaide", "5006", "SA"),
    ("Unley", "5061", "SA"),
    ("Glenelg", "5045", "SA"),
    ("Henley Beach", "5022", "SA"),
    ("Brighton", "5048", "SA"),
    ("Seacliff", "5049", "SA"),
    ("Largs Bay", "5016", "SA"),
]


def slugify_domain(suburb: str) -> str:
    """domain.com.au URL slug: lowercase, spaces -> '-'."""
    return suburb.lower().replace(" ", "-")


def slugify_realestate(suburb: str) -> str:
    """realestate.com.au URL slug: lowercase, spaces -> '+'."""
    return suburb.lower().replace(" ", "+")


# Backwards-compat alias for old call-sites.
slugify = slugify_domain
