//! gRPC service implementation. The trait `Listo` is generated by tonic-build
//! from `proto/listo.proto`. We dispatch each RPC to a small free function in
//! a focused submodule so this file stays a router, not a 1000-line god file.

mod applications;
mod conv;
mod map;
mod profit;
mod rates;
mod stats;
mod status;

use sqlx::MySqlPool;
use tonic::{Request, Response, Status};

use crate::pb;
use crate::pb::listo_server::Listo;

#[derive(Clone)]
pub struct ListoServiceImpl {
    pub pool: MySqlPool,
}

impl ListoServiceImpl {
    pub fn new(pool: MySqlPool) -> Self {
        Self { pool }
    }
}

#[tonic::async_trait]
impl Listo for ListoServiceImpl {
    async fn get_status(
        &self,
        _request: Request<pb::StatusRequest>,
    ) -> Result<Response<pb::ServerStatus>, Status> {
        status::get(&self.pool).await.map(Response::new)
    }

    async fn list_applications(
        &self,
        request: Request<pb::ListApplicationsRequest>,
    ) -> Result<Response<pb::ListApplicationsResponse>, Status> {
        applications::list(&self.pool, request.into_inner())
            .await
            .map(Response::new)
    }

    async fn get_application(
        &self,
        request: Request<pb::GetApplicationRequest>,
    ) -> Result<Response<pb::ApplicationDetail>, Status> {
        applications::detail(&self.pool, request.into_inner())
            .await
            .map(Response::new)
    }

    async fn suburb_stats(
        &self,
        request: Request<pb::SuburbStatsRequest>,
    ) -> Result<Response<pb::SuburbStatsResponse>, Status> {
        stats::suburbs(&self.pool, request.into_inner())
            .await
            .map(Response::new)
    }

    async fn trend_stats(
        &self,
        request: Request<pb::TrendStatsRequest>,
    ) -> Result<Response<pb::TrendStatsResponse>, Status> {
        stats::trends(&self.pool, request.into_inner())
            .await
            .map(Response::new)
    }

    async fn map_points(
        &self,
        request: Request<pb::MapRequest>,
    ) -> Result<Response<pb::MapResponse>, Status> {
        map::points(&self.pool, request.into_inner())
            .await
            .map(Response::new)
    }

    async fn get_current_rates(
        &self,
        _request: Request<pb::CurrentRatesRequest>,
    ) -> Result<Response<pb::CurrentRates>, Status> {
        rates::current(&self.pool).await.map(Response::new)
    }

    async fn calc_profitability(
        &self,
        request: Request<pb::CalcProfitabilityRequest>,
    ) -> Result<Response<pb::ProfitOutputs>, Status> {
        profit::calc(&self.pool, request.into_inner())
            .await
            .map(Response::new)
    }
}
