"""PDF / docx text extraction for the LLM input.

Goals:
- Fast: pymupdf is 10-50x faster than pypdf and handles complex layouts.
- Bounded: every doc_type has a `pick_pages` policy so we don't shovel
  300-page documents at the LLM. Total text is hard-capped at 12 000
  chars (~3 000 tokens) so qwen2.5's 32K context is comfortably under.
- Honest: returns `extraction_method='skipped'` + a note when a PDF has
  no extractable text (image-only scans). Caller should record that
  rather than calling the LLM with empty text.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import pymupdf  # type: ignore[import-untyped]


logger = logging.getLogger(__name__)


MAX_TEXT_CHARS = 12_000
MIN_USABLE_CHARS = 200  # below this, we treat the PDF as image-only


@dataclass
class ExtractedText:
    text: str | None
    method: str  # 'pymupdf' | 'docx' | 'skipped'
    pages_used: str | None  # e.g. '1-5,17-18' (1-indexed)
    notes: str | None  # set when text is None


# ---------- per-doc-type page selection ----------


def pick_pages(doc_type: str | None, page_count: int) -> list[int]:
    """Return 0-indexed page numbers to extract for a given doc_type.

    Conservative defaults — DAs have facts up-front and decisions at
    the end, so first-N + last-M covers most cases.
    """
    dt = (doc_type or "").lower()
    n = max(page_count, 1)

    if "decision notice" in dt or "delegated report" in dt:
        # First 3 (header + summary) + last 2 (signoff + conditions list)
        head = list(range(min(3, n)))
        tail = list(range(max(n - 2, 0), n))
        return sorted(set(head + tail))

    if "specialist report" in dt or "supporting documents" in dt:
        # Verbose planning reports — first 8 pages cover description + parties.
        return list(range(min(8, n)))

    if "stamped approved plan" in dt or dt == "plans":
        # Title-block info (architect, project name) is on page 1.
        return [0]

    if "da form 1" in dt:
        # Form 1 is usually 4-7 pages; grab first 6.
        return list(range(min(6, n)))

    if "amended" in dt:
        # Amended Form 1 — first 6 pages too.
        return list(range(min(6, n)))

    # Generic fallback: first 5 + last 1.
    head = list(range(min(5, n)))
    tail = [n - 1] if n > 6 else []
    return sorted(set(head + tail))


def _format_ranges(idxs: list[int]) -> str:
    """[0,1,2,4] (0-indexed) → '1-3,5' (1-indexed for human readability)."""
    if not idxs:
        return ""
    runs: list[tuple[int, int]] = []
    start = prev = idxs[0]
    for i in idxs[1:]:
        if i == prev + 1:
            prev = i
            continue
        runs.append((start, prev))
        start = prev = i
    runs.append((start, prev))
    return ",".join(
        f"{a + 1}" if a == b else f"{a + 1}-{b + 1}"
        for a, b in runs
    )


# ---------- extractors ----------


# Names that look auto-generated by the form designer (no semantic value
# without checkbox-position analysis we don't have yet). Skip from the
# 'FORM FIELDS' block; the LLM doesn't need 'Text_4: foo' guesses.
_GARBAGE_FIELD_NAME = (
    "undefined", "checkbox", "text_", "other_", "untitled", "field_",
)


def _is_useful_text_widget(name: str | None, value: str | None) -> bool:
    if not value or not value.strip():
        return False
    if not name:
        return False
    n = name.strip().lower()
    if n.startswith(_GARBAGE_FIELD_NAME):
        return False
    if n.isdigit():  # field name like "6" — meaningless without label context
        return False
    return True


def _extract_form_widgets(pdf: "pymupdf.Document") -> list[tuple[str, str]]:
    """Return [(field_name, value), ...] for FILLED text-type widgets only.

    Checkbox widgets are skipped — many DA Form 1 PDFs use unnamed
    auto-generated checkbox names ('undefined_6', etc.) so they're noise
    without page-position analysis. Text fields ('Name', 'Postal address',
    'Date', 'AUD $') are the high-signal ones.
    """
    out: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for page in pdf:
        widgets = page.widgets()
        if not widgets:
            continue
        for w in widgets:
            type_str = (w.field_type_string or "").lower()
            if "text" not in type_str:
                continue  # skip checkboxes, dropdowns, etc.
            name = (w.field_name or "").strip()
            value = (w.field_value or "").strip()
            if not _is_useful_text_widget(name, value):
                continue
            key = (name, value)
            if key in seen:
                continue
            seen.add(key)
            out.append((name, value))
    return out


def _format_form_block(widgets: list[tuple[str, str]]) -> str:
    """Pretty-print as a tail block we can append to the LLM input."""
    if not widgets:
        return ""
    lines = [
        "",
        "--- FORM FIELDS (filled values from the PDF's AcroForm; AUTHORITATIVE if present) ---",
    ]
    for name, value in widgets:
        # Cap each value to keep the LLM context clean
        v = value if len(value) <= 200 else value[:200] + "…"
        lines.append(f"{name}: {v}")
    lines.append("--- END FORM FIELDS ---")
    return "\n".join(lines)


def _extract_pdf(path: Path, doc_type: str | None) -> ExtractedText:
    try:
        with pymupdf.open(path) as pdf:
            n = pdf.page_count
            page_idxs = pick_pages(doc_type, n)
            chunks: list[str] = []
            for idx in page_idxs:
                if idx >= n:
                    continue
                t = pdf[idx].get_text("text")
                if t and t.strip():
                    chunks.append(t.strip())
            # Walk every page for filled widgets — they're often on
            # later pages (signature/declaration). Cheap because we only
            # touch the form dict, not the rendered text.
            form_widgets = _extract_form_widgets(pdf)
    except Exception as exc:  # noqa: BLE001 — corrupt PDFs happen
        logger.warning("pymupdf failed on %s: %s", path, exc)
        return ExtractedText(None, "skipped", None, f"pymupdf error: {exc}")

    text = "\n\n".join(chunks)
    if len(text) < MIN_USABLE_CHARS and not form_widgets:
        return ExtractedText(None, "skipped", _format_ranges(page_idxs) or None,
                             "no extractable text (likely scanned image)")

    form_block = _format_form_block(form_widgets)
    if form_block:
        text = (text + form_block) if text else form_block.lstrip()

    if len(text) > MAX_TEXT_CHARS:
        text = text[:MAX_TEXT_CHARS]
    return ExtractedText(text, "pymupdf", _format_ranges(page_idxs), None)


def extract_text_for_prompt(
    *, file_path: str | None, mime_type: str | None, doc_type: str | None
) -> ExtractedText:
    """Top-level entry — returns text + method + provenance."""
    if not file_path:
        return ExtractedText(None, "skipped", None, "no file_path on record")
    p = Path(file_path)
    if not p.exists():
        return ExtractedText(None, "skipped", None, f"file not found on disk: {file_path}")

    mt = (mime_type or "").lower()
    if mt.startswith("application/pdf") or p.suffix.lower() == ".pdf":
        return _extract_pdf(p, doc_type)

    # docx / image / html — skip in v1. Hot path is PDFs (98% of corpus).
    return ExtractedText(None, "skipped", None, f"unsupported mime: {mime_type or p.suffix}")
