"""PDF / docx text extraction for the LLM input.

Goals:
- Fast: pymupdf is 10-50x faster than pypdf and handles complex layouts.
- Bounded: every doc_type has a `pick_pages` policy so we don't shovel
  300-page documents at the LLM. Total text is hard-capped at 12 000
  chars (~3 000 tokens) so qwen2.5's 32K context is comfortably under.
- Honest: returns `extraction_method='skipped'` + a note when a PDF has
  no extractable text (image-only scans). Caller should record that
  rather than calling the LLM with empty text.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import pymupdf  # type: ignore[import-untyped]


logger = logging.getLogger(__name__)


MAX_TEXT_CHARS = 12_000
MIN_USABLE_CHARS = 200  # below this, we treat the PDF as image-only


@dataclass
class ExtractedText:
    text: str | None
    method: str  # 'pymupdf' | 'docx' | 'skipped'
    pages_used: str | None  # e.g. '1-5,17-18' (1-indexed)
    notes: str | None  # set when text is None


# ---------- per-doc-type page selection ----------


def pick_pages(doc_type: str | None, page_count: int) -> list[int]:
    """Return 0-indexed page numbers to extract for a given doc_type.

    Conservative defaults — DAs have facts up-front and decisions at
    the end, so first-N + last-M covers most cases.
    """
    dt = (doc_type or "").lower()
    n = max(page_count, 1)

    if "decision notice" in dt or "delegated report" in dt:
        # First 3 (header + summary) + last 2 (signoff + conditions list)
        head = list(range(min(3, n)))
        tail = list(range(max(n - 2, 0), n))
        return sorted(set(head + tail))

    if "specialist report" in dt or "supporting documents" in dt:
        # Verbose planning reports — first 8 pages cover description + parties.
        return list(range(min(8, n)))

    if "stamped approved plan" in dt or dt == "plans":
        # Title-block info (architect, project name) is on page 1.
        return [0]

    if "da form 1" in dt:
        # Form 1 is usually 4-7 pages; grab first 6.
        return list(range(min(6, n)))

    if "amended" in dt:
        # Amended Form 1 — first 6 pages too.
        return list(range(min(6, n)))

    # Generic fallback: first 5 + last 1.
    head = list(range(min(5, n)))
    tail = [n - 1] if n > 6 else []
    return sorted(set(head + tail))


def _format_ranges(idxs: list[int]) -> str:
    """[0,1,2,4] (0-indexed) → '1-3,5' (1-indexed for human readability)."""
    if not idxs:
        return ""
    runs: list[tuple[int, int]] = []
    start = prev = idxs[0]
    for i in idxs[1:]:
        if i == prev + 1:
            prev = i
            continue
        runs.append((start, prev))
        start = prev = i
    runs.append((start, prev))
    return ",".join(
        f"{a + 1}" if a == b else f"{a + 1}-{b + 1}"
        for a, b in runs
    )


# ---------- extractors ----------


# Names that look auto-generated by the form designer (no semantic value
# without checkbox-position analysis we don't have yet). Skip from the
# 'FORM FIELDS' block; the LLM doesn't need 'Text_4: foo' guesses.
_GARBAGE_FIELD_NAME = (
    "undefined", "checkbox", "text_", "other_", "untitled", "field_",
)


def _is_useful_text_widget(name: str | None, value: str | None) -> bool:
    if not value or not value.strip():
        return False
    if not name:
        return False
    n = name.strip().lower()
    if n.startswith(_GARBAGE_FIELD_NAME):
        return False
    if n.isdigit():  # field name like "6" — meaningless without label context
        return False
    return True


def _extract_form_widgets(pdf: "pymupdf.Document") -> list[tuple[str, str]]:
    """Return [(field_name, value), ...] for FILLED text-type widgets only.

    Checkbox widgets are skipped — many DA Form 1 PDFs use unnamed
    auto-generated checkbox names ('undefined_6', etc.) so they're noise
    without page-position analysis. Text fields ('Name', 'Postal address',
    'Date', 'AUD $') are the high-signal ones.
    """
    out: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for page in pdf:
        widgets = page.widgets()
        if not widgets:
            continue
        for w in widgets:
            type_str = (w.field_type_string or "").lower()
            if "text" not in type_str:
                continue  # skip checkboxes, dropdowns, etc.
            name = (w.field_name or "").strip()
            value = (w.field_value or "").strip()
            if not _is_useful_text_widget(name, value):
                continue
            key = (name, value)
            if key in seen:
                continue
            seen.add(key)
            out.append((name, value))
    return out


def _format_form_block(widgets: list[tuple[str, str]]) -> str:
    """Pretty-print as a tail block we can append to the LLM input."""
    if not widgets:
        return ""
    lines = [
        "",
        "--- FORM FIELDS (filled values from the PDF's AcroForm; AUTHORITATIVE if present) ---",
    ]
    for name, value in widgets:
        # Cap each value to keep the LLM context clean
        v = value if len(value) <= 200 else value[:200] + "…"
        lines.append(f"{name}: {v}")
    lines.append("--- END FORM FIELDS ---")
    return "\n".join(lines)


def _extract_pdf(path: Path, doc_type: str | None) -> ExtractedText:
    try:
        with pymupdf.open(path) as pdf:
            n = pdf.page_count
            page_idxs = pick_pages(doc_type, n)
            chunks: list[str] = []
            for idx in page_idxs:
                if idx >= n:
                    continue
                t = pdf[idx].get_text("text")
                if t and t.strip():
                    chunks.append(t.strip())
            # Walk every page for filled widgets — they're often on
            # later pages (signature/declaration). Cheap because we only
            # touch the form dict, not the rendered text.
            form_widgets = _extract_form_widgets(pdf)
    except Exception as exc:  # noqa: BLE001 — corrupt PDFs happen
        logger.warning("pymupdf failed on %s: %s", path, exc)
        return ExtractedText(None, "skipped", None, f"pymupdf error: {exc}")

    text = "\n\n".join(chunks)
    if len(text) < MIN_USABLE_CHARS and not form_widgets:
        return ExtractedText(None, "skipped", _format_ranges(page_idxs) or None,
                             "no extractable text (likely scanned image)")

    form_block = _format_form_block(form_widgets)
    if form_block:
        text = (text + form_block) if text else form_block.lstrip()

    if len(text) > MAX_TEXT_CHARS:
        text = text[:MAX_TEXT_CHARS]
    return ExtractedText(text, "pymupdf", _format_ranges(page_idxs), None)


def extract_text_for_prompt(
    *, file_path: str | None, mime_type: str | None, doc_type: str | None
) -> ExtractedText:
    """Top-level entry — returns text + method + provenance."""
    if not file_path:
        return ExtractedText(None, "skipped", None, "no file_path on record")
    p = Path(file_path)
    if not p.exists():
        return ExtractedText(None, "skipped", None, f"file not found on disk: {file_path}")

    mt = (mime_type or "").lower()
    if mt.startswith("application/pdf") or p.suffix.lower() == ".pdf":
        return _extract_pdf(p, doc_type)

    # docx / image / html — skip in v1. Hot path is PDFs (98% of corpus).
    return ExtractedText(None, "skipped", None, f"unsupported mime: {mime_type or p.suffix}")


# ---------- per-page extraction (used by features lane / chunking) ----------


@dataclass
class PerPageExtract:
    """Page-by-page text without the entity lane's pick_pages filtering or
    char cap. Empty strings for image-only pages. Used by the build-features
    lane — the chunker walks these and produces overlapping windows."""

    pages: list[str]
    method: str  # 'pymupdf' | 'docx' | 'skipped'
    notes: str | None


# Synthetic "page" size for docx (which has no real pages).
_DOCX_SYNTH_PAGE_CHARS = 3_000


def _extract_pdf_per_page(path: Path) -> PerPageExtract:
    try:
        with pymupdf.open(path) as pdf:
            pages = [(pdf[i].get_text("text") or "").strip() for i in range(pdf.page_count)]
    except Exception as exc:  # noqa: BLE001
        logger.warning("pymupdf failed on %s: %s", path, exc)
        return PerPageExtract([], "skipped", f"pymupdf error: {exc}")
    nonempty = sum(1 for p in pages if len(p) >= MIN_USABLE_CHARS)
    if nonempty == 0:
        return PerPageExtract(pages, "skipped", "no extractable text (likely scanned image)")
    return PerPageExtract(pages, "pymupdf", None)


def _extract_docx_text(path: Path) -> str | None:
    """Flat text from a .docx — stdlib only. Reads word/document.xml and
    pulls the contents of every <w:t> element in document order. Misses
    headers/footers (rarely matter for DA reports) but captures body text
    + tables, which is all we need for the Express DA Report use case."""
    import zipfile
    from xml.etree import ElementTree as ET

    try:
        with zipfile.ZipFile(path) as zf:
            with zf.open("word/document.xml") as f:
                xml_bytes = f.read()
    except (KeyError, zipfile.BadZipFile, OSError) as exc:
        logger.warning("docx unzip failed on %s: %s", path, exc)
        return None

    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError as exc:
        logger.warning("docx xml parse failed on %s: %s", path, exc)
        return None

    out: list[str] = []
    # Iterate paragraphs in document order; emit one line per paragraph,
    # joining all <w:t> runs inside it. This preserves the docx's block
    # structure better than a flat <w:t> walk.
    for para in root.iter(f"{{{ns['w']}}}p"):
        runs = [t.text or "" for t in para.iter(f"{{{ns['w']}}}t")]
        line = "".join(runs).strip()
        if line:
            out.append(line)
    return "\n".join(out) if out else None


def _extract_docx_per_page(path: Path) -> PerPageExtract:
    text = _extract_docx_text(path)
    if not text or len(text) < MIN_USABLE_CHARS:
        return PerPageExtract([], "skipped", "docx had no extractable body text")

    # Synthesize "pages" of ~3K chars each. Break on paragraph boundaries
    # (the \n we emitted) so a chunk doesn't end mid-sentence.
    pages: list[str] = []
    buf: list[str] = []
    buf_len = 0
    for para in text.split("\n"):
        para_len = len(para) + 1
        if buf_len + para_len > _DOCX_SYNTH_PAGE_CHARS and buf:
            pages.append("\n".join(buf))
            buf = []
            buf_len = 0
        buf.append(para)
        buf_len += para_len
    if buf:
        pages.append("\n".join(buf))
    return PerPageExtract(pages, "docx", None)


def extract_per_page(
    *, file_path: str | None, mime_type: str | None
) -> PerPageExtract:
    """Per-page text for the chunked extractors (build_features lane).

    Unlike `extract_text_for_prompt` this does NOT cap total chars or apply
    a pick_pages policy — the caller (chunker) is expected to window the
    output. Empty strings are preserved for image-only PDF pages so page
    indices stay aligned with the source.
    """
    if not file_path:
        return PerPageExtract([], "skipped", "no file_path on record")
    p = Path(file_path)
    if not p.exists():
        return PerPageExtract([], "skipped", f"file not found on disk: {file_path}")

    mt = (mime_type or "").lower()
    suffix = p.suffix.lower()
    if mt.startswith("application/pdf") or suffix == ".pdf":
        return _extract_pdf_per_page(p)
    if (
        mt.startswith("application/vnd.openxmlformats-officedocument.wordprocessingml")
        or suffix == ".docx"
    ):
        return _extract_docx_per_page(p)
    return PerPageExtract([], "skipped", f"unsupported mime: {mime_type or suffix}")
